lib/specwrk/web/app.rb, lib/specwrk/web/logger.rb, spec/specwrk/web/app_spec.rb, spec/specwrk/web/logger_spec.rb
+ Log to file when SPECWRK_SRV_LOG is set instead of STDOUT
+ Improve test coverage of Web::App.run!
=> Add server logging for requests

lib/specwrk/cli.rb, lib/specwrk/web/app.rb, spec/specwrk/web/app_spec.rb
=> Use the correct Webrick option

lib/specwrk/client.rb, spec/specwrk/client_spec.rb
=> Handle SSL protected srv endpoints

lib/specwrk.rb, lib/specwrk/client.rb, lib/specwrk/web/endpoints.rb, lib/specwrk/worker.rb, spec/specwrk/client_spec.rb, spec/specwrk/web/endpoints_spec.rb, spec/specwrk/worker_spec.rb
=> Worker wait for seeding

lib/specwrk/web/endpoints.rb, spec/specwrk/web/endpoints_spec.rb
This is the answer to the meaning of life. Fixes #42.
=> Don't complete examples which are not in the processing queue

lib/specwrk/cli.rb
=> Nil env var that will prevent start command from completing

config.ru, lib/specwrk/cli.rb, lib/specwrk/web/app.rb, lib/specwrk/worker.rb
Fixes #63
Fixes #61 by exposing the verbose option as an ENV var
=> Move logic out of CLI methods

docker/Dockerfile.server, docker/entrypoint.server.sh
=> Add thruster in front of puma

lib/specwrk/store.rb, lib/specwrk/web/endpoints.rb, spec/specwrk/store_spec.rb, spec/specwrk/web/endpoints_spec.rb
=> Reprocess examples stuck in processing queue

lib/specwrk/store.rb, lib/specwrk/store/base_adapter.rb, lib/specwrk/store/file_adapter.rb, lib/specwrk/web/endpoints.rb
=> Move locking to be a store adapter implementation

lib/specwrk/web/endpoints.rb
=> Don't do work before_lock in complete and pop endpoint

lib/specwrk/client.rb, lib/specwrk/web/app.rb, lib/specwrk/web/endpoints.rb, spec/specwrk/client_spec.rb, spec/specwrk/web/app_spec.rb, spec/specwrk/web/endpoints_spec.rb
=> Remove deprecated complete endpoint

lib/specwrk/cli_reporter.rb, lib/specwrk/web/endpoints.rb, spec/cli_reporter_spec.rb, spec/specwrk/web/endpoints_spec.rb
+ Make runs resumeable by only clearing stores on seed
=> Print number of examples which did not execute

lib/specwrk/cli_reporter.rb, lib/specwrk/web/endpoints.rb, spec/cli_reporter_spec.rb, spec/specwrk/web/endpoints_spec.rb
=> Report flake counts, flake re-run commands

lib/specwrk/worker/executor.rb, spec/specwrk/worker/executor_spec.rb
=> Make sure the ndjson files contain actual ndjson

README.md
=> Fix typo in license section of README

lib/specwrk/web/endpoints/base.rb, lib/specwrk/web/endpoints/report.rb, lib/specwrk/web/endpoints/shutdown.rb
=> Support lock skipping for read-only endpoints

lib/specwrk/web/endpoints/complete_and_pop.rb
This work doesn't depend on the global lock as it is read-only, and any race condition is unlikely to have any negative impact.
=> Load examples from processing before global lock

lib/specwrk/cli.rb
=> Handle default path for start and seed better

README.md, lib/specwrk/cli.rb, lib/specwrk/client.rb, spec/specwrk/client_spec.rb
=> Support retry of all client requests, configurable count

lib/specwrk/web/endpoints/base.rb
Support for threaded web servers behaving as expected. Fixes #152
=> Ensure mutex is held when a lock is expected

lib/specwrk/worker.rb, spec/specwrk/worker_spec.rb
=> Ensure next_examples are always cleared after execution
